### ISSUE TITLE
Create local site tj-config file for theme install instructions

### ISSUE THREAD

**Issue by ezekg** [ezekg/theme-juice-cli#11]
Maybe something like a YAML file. This would be used for starter theme developers to execute scripts that are relative to that theme. Example, if somebody wanted to use Grunt as a watcher over Guard.

``` yaml
watch: grunt
server: cap
vendor: composer
install:
    - composer install
    - gulp dist
```
