### ISSUE TITLE
Keep state with .tj file

### ISSUE THREAD

**Issue by ezekg** [ezekg/theme-juice-cli#3]
Not sure if this is even needed, but would make setting up a previous projects development environment simpler. But then again, it only takes a few seconds to input these settings on a `tj setup`.

``` yaml
site_name: site
dev_url: site.dev
db_host: database host
db_name: database name
db_user: database user
db_pass: database pass
```
